theme: jekyll-theme-minimal
title: ngzaharias
description: the french koala

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - about.md
  - index.md
  - recipes.md

theme: jekyll-theme-tactile
